name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: egxp/labeler@do-not-remove-labels
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

